// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtf2Za9oxvfvNQr7zphKRv1cbwVb_-8A8',
    appId: '1:878701488514:web:3d37452982f4420211079b',
    messagingSenderId: '878701488514',
    projectId: 'habit-c972a',
    authDomain: 'habit-c972a.firebaseapp.com',
    storageBucket: 'habit-c972a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5W3OIe-EzWscYQReSoyTPfzp2Tu_L0RU',
    appId: '1:878701488514:android:ebb15aa7c3801bc011079b',
    messagingSenderId: '878701488514',
    projectId: 'habit-c972a',
    storageBucket: 'habit-c972a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU0bLHMmLhiy6qrKoNwoc4S_BFHiOHhDs',
    appId: '1:878701488514:ios:32e5b19b4b1fdf1211079b',
    messagingSenderId: '878701488514',
    projectId: 'habit-c972a',
    storageBucket: 'habit-c972a.firebasestorage.app',
    iosBundleId: 'com.example.habit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU0bLHMmLhiy6qrKoNwoc4S_BFHiOHhDs',
    appId: '1:878701488514:ios:32e5b19b4b1fdf1211079b',
    messagingSenderId: '878701488514',
    projectId: 'habit-c972a',
    storageBucket: 'habit-c972a.firebasestorage.app',
    iosBundleId: 'com.example.habit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtf2Za9oxvfvNQr7zphKRv1cbwVb_-8A8',
    appId: '1:878701488514:web:0be4988519a4f8af11079b',
    messagingSenderId: '878701488514',
    projectId: 'habit-c972a',
    authDomain: 'habit-c972a.firebaseapp.com',
    storageBucket: 'habit-c972a.firebasestorage.app',
  );
}
